server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
    import:
      - application-core-local.yml

redisson:
  host: redis://localhost:6379

aws:
  s3:
    credential:
      enabled: true
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    bucket: ${BUCKET}
    attachment-path: attachment
